### PR TITLE
Feature/i follow

### PR DESCRIPTION
**Pull request by voidxnull**
In this pull request:
- New sidebar headers.
- New "I follow" block on the sidebar.
- New appearance for tags on the sidebar and in posts.
- A few refactorings related to tags.

### CODE REVIEW

**Comment by indeyets** [comment]
@voidxnull can you please reorder and stash these commits so there are no changes overwriting each other? also see comments above

**Comment by voidxnull** [comment]
Ok, will do.

**Comment by voidxnull** [comment]
Now it uses `truncate` https://github.com/Lokiedu/grapheme-utils.

**Comment by voidxnull** [comment]
I've added icons and tags for all the tag types. When we finish working on the rest of the tags I can add them to posts and the sidebar.

**Pull request merged**
